import http from './http'

export const getCountries = () => http.get('/reference/countries')
export const getCurrencies = () => http.get('/reference/currencies')
export const getLocales = () => http.get('/reference/locales')
export const getMarkets = () => http.get('/reference/markets')
export const getStatuses = (domain) => http.get('/reference/statuses', { params: { domain } })
export const getEnums = (types) => http.get('/reference/enums', { params: { types: Array.isArray(types) ? types.join(',') : types } })
export const getProductOptions = (productId) => http.get(`/reference/products/${productId}/options`)
export const getBrands = () => http.get('/brands')
export const getCategories = () => http.get('/catalog/categories')
export const getSizeGuides = () => http.get('/catalog/size-guides')
export const getCareInstructions = () => http.get('/catalog/care-instructions')
export const createCareInstruction = (payload) => http.post('/catalog/care-instructions', payload)
export const createSizeGuide = (payload) => http.post('/catalog/size-guides', payload)
export const getAttributes = () => http.get('/catalog/attributes')
export const getAttributeValues = (attributeId) => http.get(`/catalog/attributes/${attributeId}/values`)
